import argparse
import json
import re


def clean_text(text):
    text = text.lower()                     # 소문자화
    text = re.sub(r'[^\w\s]', '', text)     # 구두점 제거
    text = re.sub(r'\s+', ' ', text).strip()# 여백 정리
    return text


def compute_uniqueness_metric(candidates, ground_truths):
    """
    Args:
        candidates: List of candidate strings (generated by model)
        ground_truths: List of reference strings (ground-truth)
    """
    unique_generated = set(candidates)
    unique_references = set(ground_truths)

    if len(unique_references) == 0:
        return 0.0

    uniqueness_score = len(unique_generated) / len(unique_references)
    #uniqueness_score = len(unique_generated) / len(candidates)
    return uniqueness_score


def compute_novel_sentence_metric(candidates, training_corpus):
    """
    Args:
        candidates: List of candidate strings (generated by model)
        training_corpus: Set or list of all sentences used during training
    """
    unique_generated = set(candidates)
    training_set = set(training_corpus)

    novel_sentences = unique_generated - training_set

    if len(unique_generated) == 0:
        return 0.0

    novelty_score = len(novel_sentences) / len(unique_generated)
    return novelty_score


def compute_div(candidate, gt, training):


    uniqueness = compute_uniqueness_metric(candidate, gt)
    novelty = compute_novel_sentence_metric(candidate, training)

    print("✅ Distinct Scores: Uniqueness & Novelty")
    print(f"Uniqueness: {uniqueness:.4f}")
    print(f"Novel Sentences: {novelty:.4f}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--candidate', required=True,
                        help='Path to JSON file with format {id: [q1, q2, ..., q5]}')
    parser.add_argument('--ground-truth', required=True,
                        help='Path to G.T JSON file')
    parser.add_argument('--training', required=True,
                        help='Path to training JSON file')

    args = parser.parse_args()

    with open(args.candidate, 'r') as f:
        json_cand = json.load(f)

    with open(args.ground_truth, 'r') as f:
        json_gt = json.load(f)

    with open(args.training, 'r') as f:
        json_training = json.load(f)

    gt = json_gt['questions']
    training = json_training['questions']

    gt_questions = [clean_text(r['question']) for r in gt]
    tr_questions = [clean_text(r['question']) for r in training]

    cand = list(json_cand.values())
    cand_questions = [clean_text(q) for group in cand for q in group]

    compute_div(cand_questions, gt_questions, tr_questions)


